from colorama import Fore, Style

VERSION_MAJOR = "1"
VERSION_MINOR = "0"
VERSION_PATCH = "0"
VERSION = VERSION_MAJOR + "." + VERSION_MINOR + "." + VERSION_PATCH

RED = Fore.RED
GREEN = Fore.GREEN
YELLOW = Fore.YELLOW
BLUE = Fore.BLUE
MAGENTA = Fore.MAGENTA
CYAN = Fore.CYAN
WHITE = Fore.WHITE
BOLD = Style.BRIGHT
RESET = Style.RESET_ALL

NEWLINE = "\n"
